import "./globals.css";
import localFont from 'next/font/local'
import '../localization/i18n'

import 'swiper/css';
import 'swiper/css/pagination';
import Layout from "@/layout/layout";

import { Commissioner } from 'next/font/google'
 
const futura = Commissioner({
  weight: '400',
  subsets: ['latin' , 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-futura'
})
 
const goodTiming = localFont({
  src: '../font/good-timing-bd.ttf' ,
  weight: '700',
  variable: '--font-goodTiming'
})
const conquera = localFont({
  src: [
    {
      path: '../font/Stereo-Gothic-700.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../font/Stereo-Gothic-500.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-conquera',
})

export const metadata = {
  title: "Aito Auto",
  description: "Generated by  Abduganiev technology",
  icons: {
    icon: '/front/aitoicon.jpg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`font-futura ${futura.variable} ${conquera.variable} ${goodTiming.variable} `}>
       <Layout>
        {children}
       </Layout>
      </body>
    </html>
  );
}
