import "./globals.css";
import { Footer, Navbar } from "@/components";
import localFont from 'next/font/local'
import '../localization/i18n'

import 'swiper/css';
import 'swiper/css/pagination';
import Layout from "@/layout/layout";

const futura = localFont({
  src: [
    {
      path: '../font/FuturaBoldBT.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../font/FuturaMediumBT.ttf' ,
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-futura'
})
const goodTiming = localFont({
  src: '../font/good-timing-bd.ttf' ,
  weight: '700',
  variable: '--font-goodTiming'
})

const conquera = localFont({
  src: [
    {
      path: '../font/Stereo-Gothic-700.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../font/Stereo-Gothic-500.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-conquera',
})

export const metadata = {
  title: "Aito Auto",
  description: "Generated by create Abduganiev technology",
  icons: {
    icon: '/aitoicon.jpg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-futura ${futura.variable} ${conquera.variable} ${goodTiming.variable} `}>
       <Layout>
        {children}
       </Layout>
      </body>
    </html>
  );
}
