export { default as ImgUI } from './ui/ImgUI'
export { default as ButtonUI } from './ui/ButtonUI'


export { default as Navbar } from './navbar'
export { default as IndexBanner } from './index-banner'
export { default as AnimationBtn } from './animation-btn'
export { default as CarIndex } from './car-index'
export { default as NewsCard } from './news-card'
export { default as  AboutCard} from './aboutCard'
// export { default as Pagination } from './pagination'
export { default as TestDriveSection } from './test-drive-section'
export { default as Footer } from './footer'
export { default as ModelCharacters } from './model-characters'
export { default as SectionTitle } from './section-title'
export { default as NewsBanner } from './news-banner'
export { default as BgPage } from './bg-page'
export { default as HeaderCharacteristics } from './models/HeaderCharacteristics'
